### ISSUE TITLE
Add possibility of contraining the problem on integrated nodes

### ISSUE THREAD

**Issue by fbailly** [pyomeca/bioptim#310] opened 2021-04-12 14:59 UTC
This is a nice feature of rockit (https://gitlab.kuleuven.be/meco-software/rockit).
It allows to keep the number of shooting points low, while ensuring non-violation of path constraints on a finer grid.
The strucure of Bioptim should allow this easily.

**Comment by pariterre** [comment] 2021-05-05 20:55
That would be only available using RK (and not IRK), though.. But honestly I am not sure it is actually useful...

**Comment by fbailly** [comment] 2021-05-06 06:52
I think it is, e.g., for avoiding gimbal locks on 3D joints when single shooting integrating the solution...

**Comment by pariterre** [comment] 2021-07-13 08:46
This is now a duplicate of #249 thanks to #351

**Closed by pariterre** 2021-07-13 08:46 UTC
Labels: enhancement
