### ISSUE TITLE
Add constraint evaluation at integration points in simulate

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#318] opened 2021-04-20 15:43 UTC
Evaluate the constraint violation post-optimization to determine if all of them are respected between shooting notes.

**Comment by pariterre** [comment] 2021-05-05 20:52
Hi @EveCharbie 
What is the usecase for this since I is likely not to if the states are near the bounds?

**Comment by pariterre** [comment] 2021-07-13 08:40
Thanks to #351 it is now a duplicate of #91

**Closed by pariterre** 2021-07-13 08:40 UTC
