### ISSUE TITLE
Using MX types with bioptim functions

### ISSUE THREAD

**Issue by MennatallahRihan** [pyomeca/bioptim#583] opened 2022-11-29 19:51 UTC
Hello,
I currently have a system where my states are q,qdot,muscle length and my controls are muscle activations. I created my own equations for the states (muscle lengths) and for torques in terms of MX types. 
But I am facing two problems when running that, 

1. How to add contacts in my custom dynamics function without having qddot or torque in my variable pool (states/controls)
2.  I get this error when trying to run my code, `TypeError: unsupported operand type(s) for +: 'MX' and 'MX'`

Your help is highly appreciated,
Menna

```python

def custom_dynamics(
        states: Union[MX, SX],
        controls: Union[MX, SX],
        parameters: Union[MX, SX],
        nlp: NonLinearProgram,
) -> tuple:
    """
	Parameters
	----------
	states: Union[MX, SX]
		The state of the system
	controls: Union[MX, SX]
		The controls of the system
	parameters: Union[MX, SX]
		The parameters acting on the system
	nlp: NonLinearProgram
		A reference to the phase
	Returns
	-------
	The derivative of the states in the tuple[Union[MX, SX]] format
	"""
    tau = MX.zeros(9)
    q = DynamicsFunctions.get(nlp.states["q"], states)
    qdot = DynamicsFunctions.get(nlp.states["qdot"], states)
    lce = DynamicsFunctions.get(nlp.states["lce"], states)
    act = DynamicsFunctions.get(nlp.controls["act"], controls)

    (tau[3], tau[4], tau[5], tau[6], tau[7], tau[8], dlce) = mus.muscles(q, qdot, lce, act)
    dq = DynamicsFunctions.compute_qdot(nlp, q, qdot)
    ddq = nlp.model.ForwardDynamicsConstraintsDirect(q, qdot, tau).to_mx()

    return DynamicsEvaluation(dxdt=vertcat(dq, ddq, dlce), defects=None)


def custom_configure_my_dynamics(ocp: OptimalControlProgram, nlp: NonLinearProgram):
    """
    Tell the program which variables are states and controls.
    The user is expected to use the ConfigureProblem.configure_xxx functions.
    Parameters
    ----------
    ocp: OptimalControlProgram
        A reference to the ocp
    nlp: NonLinearProgram
        A reference to the phase
    """

    ConfigureProblem.configure_q(nlp, as_states=True, as_controls=False)
    ConfigureProblem.configure_qdot(nlp, as_states=True, as_controls=False)
    ConfigureProblem.configure_new_variable("lce",
                                            ["rGLU", "rHFL", "rHAM"],
                                            nlp, as_states=True, as_controls=False)
    ConfigureProblem.configure_new_variable("act",
                                            ["rGLU", "rHFL", "rHAM"]
                                            nlp, as_states=False, as_controls=True)

    # ConfigureProblem.configure_contact_forces(nlp, False, True)
    for ii in range(nlp.model.nbContacts()):
        ocp.implicit_constraints.add(
            ImplicitConstraintFcn.CONTACT_ACCELERATION_EQUALS_ZERO,
            with_contact=True,
            contact_index=ii,
            node=Node.ALL,
            constraint_type=ConstraintType.IMPLICIT,
            phase=nlp.phase_idx,
        )
    ConfigureProblem.configure_dynamics_function(ocp, nlp, custom_dynamics, expand=False)
```

**Comment by Ipuch** [comment] 2022-11-29 23:36
It looks like you have duplicated the contact constraint.
nlp.model.ForwardDynamicsConstraintsDirect(q, qdot, tau).to_mx() is sufficient if you want a contact.

ImplicitConstraintFcn.CONTACT_ACCELERATION_EQUALS_ZERO is only useful if you use the nlp.model.ForwardDynamics(...)

For the rest, it is very hard to say where is the exact error because I won't be able to reproduce the bug.

Do you have repo with your code I can get a look at, I may be able to spot the bug seeing the whole code or I could do a pull request to fix it.

Regards,

Pierre

**Comment by MennatallahRihan** [comment] 2022-11-30 01:09
Okay, that part makes sense. I'm adding the code to GitHub and I'll send you an invite if that's okay.

**Comment by Ipuch** [comment] 2023-01-11 19:41
Sorry, I haven't got the time to have a look.
Before implementing a muscle equilibrium dynamics, I recommend implementing a small example with one muscle and one solid (in translation) to make sure you understand well how to implement custom dynamics with bioptim. 
Let me know when you have this minimal example working.

Let me know how it went so far.

**Comment by pariterre** [comment] 2023-03-02 19:56
Closing issue as it was staled

**Closed by pariterre** 2023-03-02 19:56 UTC
Labels: question
